requests,2.25.1,['chardet (<5,>=3.0.2)', 'idna (<3,>=2.5)', 'urllib3 (<1.27,>=1.21.1)', 'certifi (>=2017.4.17)', "pyOpenSSL (>=0.14) ; extra == 'security'", "cryptography (>=1.3.4) ; extra == 'security'", "PySocks (!=1.5.7,>=1.5.6) ; extra == 'socks'", 'win-inet-pton ; (sys_platform == "win32" and python_version == "2.7") and extra == \'socks\''],[],0
pip,21.0.1,None,[{'aliases': ['CVE-2021-3572'], 'details': 'A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.', 'fixed_in': ['21.1'], 'id': 'PYSEC-2021-437', 'link': 'https://osv.dev/vulnerability/PYSEC-2021-437', 'source': 'osv'}, {'aliases': ['CVE-2021-3572'], 'details': 'A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.', 'fixed_in': ['21.1'], 'id': 'GHSA-5xp3-jfq3-5q8x', 'link': 'https://osv.dev/vulnerability/GHSA-5xp3-jfq3-5q8x', 'source': 'osv'}],0
